### ISSUE TITLE
Unhandled promise rejection: Error [TokenInvalid]: An invalid token was provided.

### ISSUE THREAD

**Issue by SergioJuniorBH** [pxsx/All-In-One-Discord-Bot#3]
System >> Starting up ...

System >> Version 10.0.0 loaded

Unhandled promise rejection: Error [TokenInvalid]: An invalid token was provided.
    at fetchRecommendedShardCount (C:\Users\sjuni\Documents\BOT\All-In-One-Discord-Bot\node_modules\discord.js\src\util\Util.js:302:40)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ShardingManager.spawn (C:\Users\sjuni\Documents\BOT\All-In-One-Discord-Bot\node_modules\discord.js\src\sharding\ShardingManager.js:190:16) {
  code: 'TokenInvalid'
}

HOW TO RESOLVE?

**Comment by pxsx** [comment]
did you configure the .env file ? 

if not this is the format for the .env file: 


DISCORD_TOKEN=
MONGO_TOKEN=
GIPHY_TOKEN=
WEBHOOK_ID=
WEBHOOK_TOKEN=
DISCORD_ID=

# Not neccessary variables
DISCORD_STATUS="github.com/Pxsx"
RADIO=
TOPGG_TOKEN=
SPOTIFY_CLIENT_ID=
SPOTIFY_CLIENT_SECRET=
LAVALINK_HOST=your-lavalink-host
LAVALINK_PASSWORD=
LAVALINK_PORT=80
OPENAI=



"TokenInvalid" is because you didnt provide a valid discord token in the file

**Comment by SergioJuniorBH** [comment]
I managed to solve it, I was getting the wrong token
